config/routes.rb
Rails.application.routes.draw do
  resources :destinations
  get 'home/index'
  resources :trips
  devise_for :users
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/destination.rb
class Destination < ApplicationRecord
  belongs_to :user
  enum destination_type: { mountain: 'Mountain',
                           lake: 'Lake',
                           river: 'River',
                           ski_mountain: 'Ski Mountain',
                           campground: 'Campground',
                           resort: 'Resort' }
end

app/models/trip.rb
class Trip < ApplicationRecord
  belongs_to :user
  validates :user, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :trips
  has_many :destinations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /destinations
  # GET /destinations.json
  def index
    @destinations = current_user.destinations
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
  end

  # GET /destinations/new
  def new
    @destination = Destination.new
  end

  # GET /destinations/1/edit
  def edit
  end

  # POST /destinations
  # POST /destinations.json
  def create
    @destination = Destination.new(destination_params.merge(user: current_user))    
    respond_to do |format|
      if @destination.save
        format.html { redirect_to @destination, notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    respond_to do |format|
      if @destination.update(destination_params)
        format.html { redirect_to @destination, notice: 'Destination was successfully updated.' }
        format.json { render :show, status: :ok, location: @destination }
      else
        format.html { render :edit }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:title, :destination_type, :note)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /trips
  # GET /trips.json
  def index
    @trips = current_user.trips
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
  end

  # GET /trips/new
  def new
    @trip = Trip.new
  end

  # GET /trips/1/edit
  def edit
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(trip_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render :show, status: :created, location: @trip }
      else
        format.html { render :new }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    respond_to do |format|
      if @trip.update(trip_params)
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { render :show, status: :ok, location: @trip }
      else
        format.html { render :edit }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip.destroy
    respond_to do |format|
      format.html { redirect_to trips_url, notice: 'Trip was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_trip
    @trip = Trip.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def trip_params
    params.require(:trip).permit(:title, :number_of_days, :number_of_nights,
                                 :commute)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/destinations/_form.html.erb
<%= form_with(model: destination, local: true) do |form| %>
  <% if destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :destination_type %>
    <%= form.select(:destination_type, Destination.destination_types.keys.map {|type| [type.titleize ,type]}) %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/destinations/edit.html.erb
<h1>Editing Destination</h1>

<%= render 'form', destination: @destination %>

<%= link_to 'Show', @destination %> |
<%= link_to 'Back', destinations_path %>

app/views/destinations/index.html.erb
<h1>Destinations</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Type</th>
      <th>Note</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @destinations.each do |destination| %>
      <tr>
        <td><%= destination.title %></td>
        <td><%= destination.destination_type %></td>
        <td><%= destination.note %></td>
        <td><%= link_to 'Show', destination %></td>
        <td><%= link_to 'Edit', edit_destination_path(destination) %></td>
        <td><%= link_to 'Destroy', destination, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Destination', new_destination_path %>

app/views/destinations/new.html.erb
<h1>New Destination</h1>

<%= render 'form', destination: @destination %>

<%= link_to 'Back', destinations_path %>

app/views/destinations/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @destination.title %>
</p>

<p>
  <strong>Type:</strong>
  <%= @destination.destination_type %>
</p>

<p>
  <strong>Note:</strong>
  <%= @destination.note %>
</p>

<%= link_to 'Edit', edit_destination_path(@destination) %> |
<%= link_to 'Back', destinations_path %>

app/views/home/index.html.erb
<h1>Welcome To Weekend Planner</h1>
<p>Weekend planner helps you plan and optimize your weekend outdoor adventures</p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Home <span class="sr-only">(current)</span></a>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to 'Trip Planning', trips_path, class: "nav-link" %></li>
          <%= link_to 'Destinations', destinations_path, class: "nav-link" %></li>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Logged in as <strong><%= current_user.email %></strong>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Edit profile', edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "dropdown-item"%>
          </div>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to 'Sign in', new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %></li>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Weekendplanner" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Weekendplanner" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/trips/_form.html.erb
<%= form_with(model: trip, local: true) do |form| %>
  <% if trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% trip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :number_of_days %>
    <%= form.number_field :number_of_days %>
  </div>

  <div class="field">
    <%= form.label :number_of_nights %>
    <%= form.number_field :number_of_nights %>
  </div>

  <div class="field">
    <%= form.label :commute, value: 'Commute (hours)' %>
    <%= form.number_field :commute %>
  </div>



  <div class="actions">
    <%= form.submit 'Submit', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/trips/edit.html.erb
<h1>Editing Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Show', @trip %> |
<%= link_to 'Back', trips_path %>

app/views/trips/index.html.erb
<h1>Trips</h1>

<table class="table table-hover table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Days</th>
      <th>Nights</th>
      <th>Commute(hours)</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td><%= trip.title %></td>
        <td><%= trip.number_of_days %></td>
        <td><%= trip.number_of_nights %></td>
        <td><%= trip.commute %></td>
        <td><%= link_to 'Show', trip %></td>
        <td><%= link_to 'Edit', edit_trip_path(trip) %></td>
        <td><%= link_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Trip', new_trip_path %>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= render 'form', trip: @trip %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @trip.title %>
</p>
<p>
  <strong>Commute (hours):</strong>
  <%= @trip.commute %>
</p>
<p>
  <strong>Days:</strong>
  <%= @trip.number_of_days %>
</p>
<p>
  <strong>Nights:</strong>
  <%= @trip.number_of_nights %>
</p>

<%= link_to 'Edit', edit_trip_path(@trip) %> |
<%= link_to 'Back', trips_path %>